window.SMART_FARM_CROPS = [
  {
    id: "apple",
    name: "사과",
    group: "과수류",
    summary: "품종별 착색, 온도, 토양 pH를 세밀하게 관리합니다.",
    varieties: [
      {
        id: "fuji",
        name: "후지",
        alias: "부사",
        temp: [18, 24],
        humidity: [55, 70],
        soilMoisture: [35, 55],
        soilPh: [5.8, 6.3],
        co2: [500, 900],
        light: [6, 8],
        planting: "토양이 녹는 즉시, 늦어도 3월 중·하순",
        notes: "30 C 이상에서는 과실비대와 꽃눈 형성이 나빠질 수 있습니다.",
      },
      {
        id: "hongro",
        name: "홍로",
        alias: "추석 전후 수확",
        temp: [18, 24],
        humidity: [55, 68],
        soilMoisture: [35, 55],
        soilPh: [5.8, 6.3],
        co2: [500, 900],
        light: [6, 8],
        planting: "봄 심기 기준 3월 중·하순 이전",
        notes: "착색기에는 야간 온도와 일교차 관리가 중요합니다.",
      },
      {
        id: "gamhong",
        name: "감홍",
        alias: "고당도 품종",
        temp: [18, 23],
        humidity: [55, 68],
        soilMoisture: [35, 52],
        soilPh: [5.8, 6.3],
        co2: [500, 900],
        light: [6, 8],
        planting: "토양 해빙 후 이른 봄 정식",
        notes: "당도와 착색을 위해 과습과 과도한 질소를 피합니다.",
      },
    ],
  },
  {
    id: "strawberry",
    name: "딸기",
    group: "과채류",
    summary: "과습과 환기를 중심으로 꽃, 과실, 잎 상태를 관리합니다.",
    varieties: [
      {
        id: "seolhyang",
        name: "설향",
        alias: "국내 대표 품종",
        temp: [17, 23],
        humidity: [60, 75],
        soilMoisture: [45, 65],
        soilPh: [5.5, 6.5],
        co2: [600, 1000],
        light: [8, 10],
        planting: "육묘 후 9월 중순-10월 상순 정식",
        notes: "과습과 낮은 환기는 잿빛곰팡이병 위험을 키웁니다.",
      },
      {
        id: "maehyang",
        name: "매향",
        alias: "수출 선호 품종",
        temp: [17, 22],
        humidity: [58, 72],
        soilMoisture: [45, 63],
        soilPh: [5.5, 6.5],
        co2: [600, 1000],
        light: [8, 10],
        planting: "9월 하순 전후 정식",
        notes: "과실 경도 유지를 위해 야간 습도를 낮게 관리합니다.",
      },
    ],
  },
  {
    id: "tomato",
    name: "토마토",
    group: "과채류",
    summary: "온도, CO2, 광량 균형이 착과와 과실 비대에 중요합니다.",
    varieties: [
      {
        id: "cherry",
        name: "대추방울토마토",
        alias: "소과종",
        temp: [20, 27],
        humidity: [55, 70],
        soilMoisture: [45, 65],
        soilPh: [6.0, 6.8],
        co2: [700, 1200],
        light: [8, 10],
        planting: "시설재배 기준 작형에 따라 연중 조정",
        notes: "야간 온도와 습도 편차가 크면 착과와 병해 관리가 어려워집니다.",
      },
      {
        id: "beefsteak",
        name: "완숙토마토",
        alias: "대과종",
        temp: [19, 26],
        humidity: [55, 70],
        soilMoisture: [45, 65],
        soilPh: [6.0, 6.8],
        co2: [700, 1200],
        light: [8, 10],
        planting: "시설재배 기준 작형별 정식",
        notes: "과실 비대를 위해 수분과 EC 변동을 완만하게 유지합니다.",
      },
    ],
  },
  {
    id: "cucumber",
    name: "오이",
    group: "과채류",
    summary: "수분 변동과 고온 스트레스를 줄이는 제어가 중요합니다.",
    varieties: [
      {
        id: "baekdadagi",
        name: "백다다기",
        alias: "신선 소비",
        temp: [22, 28],
        humidity: [65, 80],
        soilMoisture: [50, 70],
        soilPh: [6.0, 6.8],
        co2: [600, 1000],
        light: [7, 9],
        planting: "시설재배 기준 봄, 여름, 가을 작형 선택",
        notes: "급격한 수분 변동은 곡과와 생육 불량을 만들 수 있습니다.",
      },
    ],
  },
  {
    id: "lettuce",
    name: "상추",
    group: "엽채류",
    summary: "고온기 추대 방지와 잎 품질 관리에 집중합니다.",
    varieties: [
      {
        id: "green-leaf",
        name: "청치마",
        alias: "잎상추",
        temp: [15, 22],
        humidity: [55, 75],
        soilMoisture: [45, 65],
        soilPh: [6.0, 7.0],
        co2: [500, 900],
        light: [5, 7],
        planting: "시설재배 기준 연중 가능, 고온기 차광 필요",
        notes: "고온에서는 추대와 잎 품질 저하가 빨라집니다.",
      },
    ],
  },
  {
    id: "paprika",
    name: "파프리카",
    group: "과채류",
    summary: "장기재배에서 온도, 광량, CO2 균형을 유지합니다.",
    varieties: [
      {
        id: "red-paprika",
        name: "레드 파프리카",
        alias: "착색형",
        temp: [21, 26],
        humidity: [60, 75],
        soilMoisture: [45, 65],
        soilPh: [5.8, 6.5],
        co2: [700, 1200],
        light: [8, 10],
        planting: "시설 장기재배 기준 8-9월 정식이 일반적",
        notes: "광량, 온도, CO2 균형이 과실 비대와 착색에 중요합니다.",
      },
    ],
  },
  {
    id: "cabbage",
    name: "배추",
    group: "엽채류",
    summary: "결구기 온도와 토양수분을 중심으로 관리합니다.",
    varieties: [
      {
        id: "fall-cabbage",
        name: "가을배추",
        alias: "노지·시설 겸용",
        temp: [15, 20],
        humidity: [55, 75],
        soilMoisture: [45, 65],
        soilPh: [5.5, 6.8],
        co2: [450, 800],
        light: [5, 8],
        planting: "봄배추와 가을배추 작형별 파종일 분리",
        notes: "결구기 고온은 품질과 결구 상태에 영향을 줍니다.",
      },
    ],
  },
  {
    id: "potato",
    name: "감자",
    group: "근채류",
    summary: "토양 과습과 괴경 비대 시기 수분 관리를 중점으로 봅니다.",
    varieties: [
      {
        id: "sumi",
        name: "수미",
        alias: "대표 식용 품종",
        temp: [15, 23],
        humidity: [50, 70],
        soilMoisture: [40, 60],
        soilPh: [5.0, 6.0],
        co2: [450, 800],
        light: [6, 8],
        planting: "봄재배는 지역별로 2월 하순-4월 상순",
        notes: "토양 과습은 괴경 부패와 병 발생 위험을 높입니다.",
      },
    ],
  },
];
